version: "3"

services:
  postgis:
    container_name: "cy_db"
    image: "postgis/postgis"
    env_file: .env
    ports:
      - "5432:5432"

  mongo:
    container_name: cy_mongo
    image: "mongo"
    env_file: .env
    command: "mongod --auth --storageEngine wiredTiger"
    ports:
      - "27017:27017"
