version: "3"

services:
  postgis:
        container_name: cyan-mills
        environment:
            - POSTGRES_PASSWORD=docker
        ports:
            - '5432:5432'
        image: postgis/postgis

# OR:     docker run --name cyan-mills -e POSTGRES_PASSWORD=docker POSTGRES_DB=cyan-challenge -p 5432:5432 -d postgis/postgis

